"""crm lead capture foundation

Revision ID: 382bf4a1ede1
Revises: 23725a908e3d
Create Date: 2026-08-08 23:35:54.857650
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "382bf4a1ede1"
down_revision: str | None = "23725a908e3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "idempotency_key"),
    )
    op.create_index("ix_idempotency_expires", "idempotency_keys", ["expires_at"], unique=False)
    op.add_column("leads", sa.Column("source_detail", sa.String(length=200), nullable=True))
    op.add_column("leads", sa.Column("project_city", sa.String(length=120), nullable=True))
    op.add_column("leads", sa.Column("project_type", sa.String(length=120), nullable=True))
    op.add_column("leads", sa.Column("expected_capacity", sa.String(length=120), nullable=True))
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid"
    op.execute(sa.text('ALTER TABLE "idempotency_keys" ENABLE ROW LEVEL SECURITY'))
    op.execute(sa.text('ALTER TABLE "idempotency_keys" FORCE ROW LEVEL SECURITY'))
    op.execute(
        sa.text(
            'CREATE POLICY tenant_isolation ON "idempotency_keys" '
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leads", "expected_capacity")
    op.drop_column("leads", "project_type")
    op.drop_column("leads", "project_city")
    op.drop_column("leads", "source_detail")
    op.drop_index("ix_idempotency_expires", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
