"""enforce lead money pair

Revision ID: 470b25de338d
Revises: 382bf4a1ede1
Create Date: 2026-08-08 23:51:48.653027
"""

from collections.abc import Sequence

from alembic import op

revision: str = "470b25de338d"
down_revision: str | None = "382bf4a1ede1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "leads_money_pair_check",
        "leads",
        "(estimated_value IS NULL AND currency IS NULL) OR "
        "(estimated_value IS NOT NULL AND currency IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("leads_money_pair_check", "leads", type_="check")
    # ### end Alembic commands ###
