"""identity and data foundation

Revision ID: ba2697bc4eeb
Revises: 20260808_0001
Create Date: 2026-08-08 22:08:56.172908
"""

from collections.abc import Sequence
from uuid import UUID

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ba2697bc4eeb"
down_revision: str | None = "20260808_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("default_locale", sa.String(length=20), server_default="en", nullable=False),
        sa.Column(
            "default_timezone", sa.String(length=64), server_default="Asia/Jakarta", nullable=False
        ),
        sa.Column("default_currency", sa.String(length=3), server_default="IDR", nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active','suspended','closed')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "identity_provider", sa.String(length=50), server_default="supabase", nullable=False
        ),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active','disabled')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_provider", "external_subject"),
    )
    op.create_table(
        "agent_configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_key", sa.String(length=80), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("instructions_ref", sa.String(length=255), nullable=False),
        sa.Column("output_schema_version", sa.String(length=50), nullable=False),
        sa.Column(
            "runtime_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft','active','retired')"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "agent_key", "version_number"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_tenant_created", "audit_events", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("role IN ('admin','sales')"),
        sa.CheckConstraint("status IN ('invited','active','suspended')"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id"),
    )
    op.create_index(
        "ix_memberships_tenant_role", "tenant_memberships", ["tenant_id", "role"], unique=False
    )
    op.create_index(
        "ix_memberships_user_status", "tenant_memberships", ["user_id", "status"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.String(length=250), nullable=False),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("preferred_language", sa.String(length=20), nullable=True),
        sa.Column(
            "lifecycle_stage", sa.String(length=30), server_default="prospect", nullable=False
        ),
        sa.Column("owner_membership_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("lifecycle_stage IN ('prospect','qualified','customer','inactive')"),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["tenant_memberships.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_organizations_tenant_domain", "organizations", ["tenant_id", "domain"], unique=False
    )
    op.create_index(
        "ix_organizations_tenant_name", "organizations", ["tenant_id", "display_name"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(length=120), nullable=True),
        sa.Column("last_name", sa.String(length=120), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("whatsapp_e164", sa.String(length=20), nullable=True),
        sa.Column("preferred_language", sa.String(length=20), nullable=True),
        sa.Column(
            "marketing_consent_status",
            sa.String(length=30),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("do_not_contact", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("owner_membership_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "first_name IS NOT NULL OR last_name IS NOT NULL "
            "OR email IS NOT NULL OR phone_e164 IS NOT NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["tenant_memberships.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_contacts_tenant_email", "contacts", ["tenant_id", "email"], unique=False)
    op.create_index(
        "ix_contacts_tenant_phone", "contacts", ["tenant_id", "phone_e164"], unique=False
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("source_channel", sa.String(length=30), nullable=False),
        sa.Column("inquiry_summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="new", nullable=False),
        sa.Column("priority", sa.String(length=20), server_default="normal", nullable=False),
        sa.Column("owner_membership_id", sa.UUID(), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("target_timeline", sa.String(length=100), nullable=True),
        sa.Column("project_country_code", sa.String(length=2), nullable=True),
        sa.Column(
            "requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("qualification_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("priority IN ('low','normal','high','urgent')"),
        sa.CheckConstraint(
            "status IN ('new','qualifying','qualified','nurture',"
            "'disqualified','converted','archived')"
        ),
        sa.CheckConstraint("estimated_value IS NULL OR estimated_value >= 0"),
        sa.CheckConstraint("qualification_score IS NULL OR qualification_score BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["tenant_memberships.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_leads_tenant_work_queue",
        "leads",
        ["tenant_id", "status", "owner_membership_id", "priority"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_configuration_id", sa.UUID(), nullable=False),
        sa.Column("workflow_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="queued", nullable=False),
        sa.Column("initiated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provider_type", sa.String(length=120), nullable=True),
        sa.Column("model_id", sa.String(length=120), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message_safe", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','awaiting_approval','succeeded','failed','cancelled')"
        ),
        sa.ForeignKeyConstraint(
            ["agent_configuration_id"],
            ["agent_configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_runs_tenant_status_created",
        "agent_runs",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("primary_contact_id", sa.UUID(), nullable=True),
        sa.Column("source_lead_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("stage", sa.String(length=40), server_default="qualification", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column(
            "probability", sa.Numeric(precision=5, scale=2), server_default="10", nullable=False
        ),
        sa.Column(
            "estimated_value", sa.Numeric(precision=19, scale=4), server_default="0", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), server_default="IDR", nullable=False),
        sa.Column("expected_close_date", sa.Date(), nullable=True),
        sa.Column(
            "requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("owner_membership_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("status IN ('open','won','lost','cancelled')"),
        sa.CheckConstraint("estimated_value >= 0"),
        sa.CheckConstraint("probability BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_membership_id"],
            ["tenant_memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_lead_id"),
    )
    op.create_index(
        "ix_opportunities_tenant_pipeline",
        "opportunities",
        ["tenant_id", "status", "stage", "expected_close_date"],
        unique=False,
    )
    op.create_table(
        "lead_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("assessment_version", sa.Integer(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("need_summary", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column(
            "missing_information",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("review_status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "review_status IN ('not_required','pending','approved','rejected','superseded')"
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1"),
        sa.CheckConstraint("score BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lead_id", "assessment_version"),
    )
    op.create_index(
        "ix_assessments_tenant_review",
        "lead_assessments",
        ["tenant_id", "review_status", "created_at"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="open", nullable=False),
        sa.Column("priority", sa.String(length=20), server_default="normal", nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("priority IN ('low','normal','high','urgent')"),
        sa.CheckConstraint("status IN ('open','in_progress','completed','cancelled')"),
        sa.CheckConstraint(
            "lead_id IS NOT NULL OR opportunity_id IS NOT NULL OR organization_id IS NOT NULL"
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["tenant_memberships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tasks_tenant_assignee_due",
        "tasks",
        ["tenant_id", "assigned_to", "status", "due_at"],
        unique=False,
    )
    tenant = sa.table(
        "tenants",
        sa.column("id", sa.UUID()),
        sa.column("slug", sa.String()),
        sa.column("name", sa.String()),
    )
    user = sa.table(
        "users",
        sa.column("id", sa.UUID()),
        sa.column("identity_provider", sa.String()),
        sa.column("external_subject", sa.String()),
        sa.column("email", sa.String()),
        sa.column("display_name", sa.String()),
    )
    membership = sa.table(
        "tenant_memberships",
        sa.column("id", sa.UUID()),
        sa.column("tenant_id", sa.UUID()),
        sa.column("user_id", sa.UUID()),
        sa.column("role", sa.String()),
        sa.column("status", sa.String()),
        sa.column("joined_at", sa.DateTime(timezone=True)),
    )
    sari_arta_id = UUID("10000000-0000-4000-8000-000000000001")
    admin_id = UUID("20000000-0000-4000-8000-000000000001")
    sales_id = UUID("20000000-0000-4000-8000-000000000002")
    op.bulk_insert(
        tenant,
        [{"id": sari_arta_id, "slug": "sari-arta", "name": "Sari Arta (Demo)"}],
    )
    op.bulk_insert(
        user,
        [
            {
                "id": admin_id,
                "identity_provider": "supabase",
                "external_subject": "30000000-0000-4000-8000-000000000001",
                "email": "admin@sari-arta.example",
                "display_name": "Sari Arta Demo Admin",
            },
            {
                "id": sales_id,
                "identity_provider": "supabase",
                "external_subject": "30000000-0000-4000-8000-000000000002",
                "email": "sales@sari-arta.example",
                "display_name": "Sari Arta Demo Sales",
            },
        ],
    )
    op.bulk_insert(
        membership,
        [
            {
                "id": UUID("40000000-0000-4000-8000-000000000001"),
                "tenant_id": sari_arta_id,
                "user_id": admin_id,
                "role": "admin",
                "status": "active",
                "joined_at": sa.func.now(),
            },
            {
                "id": UUID("40000000-0000-4000-8000-000000000002"),
                "tenant_id": sari_arta_id,
                "user_id": sales_id,
                "role": "sales",
                "status": "active",
                "joined_at": sa.func.now(),
            },
        ],
        multiinsert=False,
    )

    tenant_tables = (
        "agent_configurations",
        "organizations",
        "contacts",
        "leads",
        "agent_runs",
        "opportunities",
        "lead_assessments",
        "tasks",
    )
    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid"
    for table_name in tenant_tables:
        op.execute(sa.text(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                f'CREATE POLICY tenant_isolation ON "{table_name}" '
                f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_tenant_assignee_due", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_assessments_tenant_review", table_name="lead_assessments")
    op.drop_table("lead_assessments")
    op.drop_index("ix_opportunities_tenant_pipeline", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_agent_runs_tenant_status_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_leads_tenant_work_queue", table_name="leads")
    op.drop_table("leads")
    op.drop_index("ix_contacts_tenant_phone", table_name="contacts")
    op.drop_index("ix_contacts_tenant_email", table_name="contacts")
    op.drop_table("contacts")
    op.drop_index("ix_organizations_tenant_name", table_name="organizations")
    op.drop_index("ix_organizations_tenant_domain", table_name="organizations")
    op.drop_table("organizations")
    op.drop_index("ix_memberships_user_status", table_name="tenant_memberships")
    op.drop_index("ix_memberships_tenant_role", table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_index("ix_audit_tenant_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("agent_configurations")
    op.drop_table("users")
    op.drop_table("tenants")
    # ### end Alembic commands ###
